### ISSUE TITLE
Runtime error when trying to connect to server

### ISSUE THREAD

**Issue by MAGICCC** [evilsocket/shellz#10]
Hello,

Thanks for adding the ssh-agent integration, but this doesn't work for me

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b367d]

goroutine 14 [running]:
github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc4201a8080, 0xc4201a2000,
 0x0, 0xa)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh/client_auth.go:63 +0x2dd
github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc4201a8080, 0xc420020e20, 0x
10, 0xc4201a2000, 0x0, 0x0)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh/client.go:113 +0x2c4
github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh.NewClientConn(0x97b7c0, 0xc4201a0000, 0xc420020e20, 0x10, 0x
c420149ad0, 0x97b7c0, 0xc4201a0000, 0x0, 0x0, 0x1, ...)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh/client.go:83 +0x100
github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh.Dial(0x8d58a8, 0x3, 0xc420020e20, 0x10, 0xc420149ad0, 0x0, 0x0, 0x0)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/golang.org/x/crypto/ssh/client.go:177 +0xb3
github.com/evilsocket/shellz/session.NewSSH.func1(0x0, 0x0)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/session/ssh.go:49 +0x13a
github.com/evilsocket/shellz/vendor/github.com/evilsocket/islazy/async.WithTimeout.func1(0xc42009a540, 0xc420119c40)
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/github.com/evilsocket/islazy/async/timeout.go:16 +0x27
created by github.com/evilsocket/shellz/vendor/github.com/evilsocket/islazy/async.WithTimeout
        /home/evilsocket/gocode/src/github.com/evilsocket/shellz/vendor/github.com/evilsocket/islazy/async/timeout.go:15 +0x92
```

**Comment by evilsocket** [comment]
can you share both your identity and shell json files?

**Comment by MAGICCC** [comment]
Yes, here you go

`cat .shellz/idents/default.json`
```
{
        "name": "default",
        "username": "root",
        "key": "~/.ssh/id_rsa"
}
```

`cat .shellz/shells/hetzner-magic.json`
```
{
        "name": "hetzner-magic",
        "host": "95.216.141.xxx",
        "groups": ["hetzner", "all"],
        "port": 22,
        "identity": "default"
}
```

`ls -lah ~/.ssh/id_rsa`
```
-r-------- 1 magic magic 444 Sep 16 19:29 /home/magic/.ssh/id_rsa
```

The key is a ed25519 one

**Comment by evilsocket** [comment]
i'm sorry but i'm not following, you're not using the agent? as per README, you should put `@agent` as the key field

**Comment by evilsocket** [comment]
(the fact it crashes it's even weirder tho)

**Comment by MAGICCC** [comment]
Oh, welp now it's working

**Comment by evilsocket** [comment]
LOL

**Comment by evilsocket** [comment]
WTF IS WRONG WITH YOUR SSH PRIVATE KEY!?!? XD

**Comment by evilsocket** [comment]
(now i really want to see how i reproduce and debug this ... willing to send your private key? :'D)

**Comment by MAGICCC** [comment]
> 
> 
> (now i really want to see how i reproduce and debug this ... willing to send your private key? :'D)

nah :)
I only had ~/.ssh/id_rsa in my ident.json and somehow it wanted to use the agent or so

**Comment by evilsocket** [comment]
lol glad it works :+1:
